spring:
  application:
    name: authservice
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:classpath:.env[.properties]
  cloud:
    config:
      fail-fast: false # Config 없이 기동

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          # default
          max-active: 8
          max-idle: 8
          min-idle: 0
server:
  port: 19091
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8000/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-minutes: 30
  refresh-token:
    expiration-days: 14
  issuer: pagely

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

logging:
  level:
    com.pagely.authservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  tracing:
    sampling:
      probability: 1.0    # 학습 단계 100% 샘플링. 운영은 0.1 (10%)
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
